-- Create the waitlist table
create table waitlist (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
